# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(1282, 462)
        Application.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(Application)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Ed_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Ed_label.setFont(font)
        self.Ed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Ed_label.setObjectName("Ed_label")
        self.verticalLayout_2.addWidget(self.Ed_label)
        self.Ed_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ed_lineEdit.sizePolicy().hasHeightForWidth())
        self.Ed_lineEdit.setSizePolicy(sizePolicy)
        self.Ed_lineEdit.setMinimumSize(QtCore.QSize(150, 50))
        self.Ed_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Ed_lineEdit.setFont(font)
        self.Ed_lineEdit.setText("")
        self.Ed_lineEdit.setReadOnly(True)
        self.Ed_lineEdit.setObjectName("Ed_lineEdit")
        self.verticalLayout_2.addWidget(self.Ed_lineEdit)
        self.Ed_silder = QtWidgets.QSlider(self.centralwidget)
        self.Ed_silder.setMinimumSize(QtCore.QSize(150, 50))
        self.Ed_silder.setMaximum(112)
        self.Ed_silder.setOrientation(QtCore.Qt.Horizontal)
        self.Ed_silder.setObjectName("Ed_silder")
        self.verticalLayout_2.addWidget(self.Ed_silder)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Nd0_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Nd0_label.setFont(font)
        self.Nd0_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Nd0_label.setObjectName("Nd0_label")
        self.verticalLayout_3.addWidget(self.Nd0_label)
        self.Nd0_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nd0_lineEdit.sizePolicy().hasHeightForWidth())
        self.Nd0_lineEdit.setSizePolicy(sizePolicy)
        self.Nd0_lineEdit.setMinimumSize(QtCore.QSize(150, 50))
        self.Nd0_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Nd0_lineEdit.setFont(font)
        self.Nd0_lineEdit.setText("")
        self.Nd0_lineEdit.setReadOnly(True)
        self.Nd0_lineEdit.setObjectName("Nd0_lineEdit")
        self.verticalLayout_3.addWidget(self.Nd0_lineEdit)
        self.Nd0_slider = QtWidgets.QSlider(self.centralwidget)
        self.Nd0_slider.setMinimumSize(QtCore.QSize(150, 50))
        self.Nd0_slider.setMinimum(1)
        self.Nd0_slider.setMaximum(7)
        self.Nd0_slider.setSingleStep(1)
        self.Nd0_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Nd0_slider.setObjectName("Nd0_slider")
        self.verticalLayout_3.addWidget(self.Nd0_slider)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 3, 1)
        styles = {'color': 'r', 'font-size': '15px', 'font-weight': 'bold'}


        self.plot1 = PlotWidget(self.centralwidget)
        fnt = QtGui.QFont("Times", 10, QtGui.QFont.Bold)

        self.plot1.getAxis("bottom").setTickFont(fnt)
        self.plot1.getAxis("left").setTickFont(fnt)
        self.plot1.setMinimumSize(QtCore.QSize(200, 200))
        self.plot1.setObjectName("plot1")
        self.gridLayout.addWidget(self.plot1, 0, 0, 1, 2)
        self.plot1.getAxis("left").enableAutoSIPrefix(False)
        self.plot1.setLabel('left', 'Concentration', **styles)
        self.plot1.setLabel('bottom', 'Temperature, K', **styles)

        self.plot2 = PlotWidget(self.centralwidget)
        self.plot2.setMinimumSize(QtCore.QSize(200, 200))
        self.plot2.setObjectName("plot2")
        self.plot2.getAxis("bottom").setTickFont(fnt)
        self.plot2.getAxis("left").setTickFont(fnt)

        self.plot2.setLabel('left', 'Fermi level, eV', **styles)
        self.plot2.setLabel('bottom', 'Temperature, K', **styles)

        self.gridLayout.addWidget(self.plot2, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        Application.setCentralWidget(self.centralwidget)

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)
        self.plot1.setBackground('w')
        self.plot2.setBackground('w')

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "SOEAH"))
        self.Ed_label.setText(_translate("Application", "E_d"))
        self.Nd0_label.setText(_translate("Application", "N_d0"))
